---


    - name: Update and upgrade apt packages for Ubuntu Servers
      apt: upgrade=yes update_cache=yes cache_valid_time=86400
      when: ansible_os_family == "Debian"

    - name: Update and Upgrade all packages for Redhat servers
      yum: name=* state=latest
      when: ansible_os_family == "RedHat"

    - name: Create a common directory
      file: path=/etc/devops_directory state=directory mode=0755

    - name: Install NFS on Ubuntu server
      apt: name=nfs-client
      when: ansible_os_family == "Debian"

    - name: Install NFS on RedHat server
      yum: name=nfs-utils
      when: ansible_os_family == "RedHat"

    - name: Start NFS on RedHat Server
      service: name=nfs-server state=started enabled=yes
      when: ansible_os_family == "RedHat"

    - name: Set Timezone to Europe/London
      timezone: name=Europe/London

